/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.0.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "influ-news"
configureProject("apps")

fun configureProject(path: String) =
    File("${rootDir}/$path")
        .listFiles()!!
        .filter { isGradleProject(it, path) }
        .map { it.name }
        .map { name ->
            include(":$name")
            project(":$name").projectDir = File("$path/$name")
        }

fun isGradleProject(file: File, path: String) =
    if (!file.isDirectory) false
    else File("$path/${file.name}/build.gradle.kts").exists()
            || File("$rootDir/$path/${file.name}/build.gradle.kts").exists()
