spring:
  profiles:
    active: dev

  servlet:
    multipart:
      max-file-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SECRET_DB_URL}
    username: ${SECRET_DB_USERNAME}
    password: ${SECRET_DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        endpoint: ${AWS_ENDPOINT}
        region: ${AWS_REGION}
      region:
        static: ${AWS_REGION}

app:
  images:
    storage:
      bucket-name: ${RESCALED_IMAGES_BUCKET}

server:
  port: 8080

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
      base-path: /
  endpoint:
    health:
      show-components: always
  health:
    defaults:
      enabled: false
    db:
      enabled: true

---
spring:
  config.activate.on-profile: dev

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true

app:
  http.cors.allowed-origins: "*"

management:
  endpoints:
    web:
      exposure:
        include: health, info, env, metrics

---
spring:
  config.activate.on-profile: prod

management:
  endpoint:
    health:
      db:
        enabled: true