spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SECRET_DB_URL:jdbc:postgresql://localhost:5432/influ-news}
    username: ${SECRET_DB_USERNAME:postgres}
    password: ${SECRET_DB_PASSWORD:admin}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

server:
  port: 8080

