/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {

}

application {
    // Define the main class for the application.
    mainClass = "com.newsnow.platform.imagerescale.ImageRescaleApplication"
}
