name: Image Rescale PR pipeline
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'apps/image-rescale/**'
    types: [synchronize, opened, reopened, ready_for_review]

# Ensures that only a single job or workflow using the same concurrency group (branch) will run at a time
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: write
  pull-requests: write

jobs:
  tests:
    name: PR pipeline for image-rescale
    uses: ./.github/workflows/job-tests.yml
    with:
      app_name: image-rescale
    secrets: inherit
