on:
  # Allows to call this job from another pipeline
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    # Map the workflow outputs to job outputs
    outputs:
      test-results:
        value: ${{ jobs.tests.outputs.test-results }}

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  WORKING_DIRECTORY: '/apps/${{ inputs.app_name }}'

name: Testing pipeline
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
    permissions:
      checks: write
      pull-requests: write
    outputs:
      test-results: ${{ steps.test-results.outputs.content }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup java version
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: build
        run: make build

      - name: tests
        run: make tests

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Test Results
          path: |
            **/build/test-results/

      - name: Publish Test Results
        id: publish-test-results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/test-results/**/*.xml'

      - name: Output test results
        id: test-results
        run: |
          echo 'content=${{ steps.publish-test-results.outputs.json }}' >> $GITHUB_OUTPUT
